// Self-Efficacy Quick Assessment Data Model
export const selfEfficacyQuickAssessment = {
  id: "self-efficacy-quick",
  title: "Self-Efficacy Quick Assessment",
  description:
    "A brief assessment to measure your belief in your ability to succeed in specific situations and accomplish tasks.",
  category: "self-efficacy",
  estimatedTime: "5 min",
  totalQuestions: 8,
  questions: [
    {
      id: 1,
      text: "When faced with a difficult challenge in sports or academics, I believe I can find a way to overcome it.",
      type: "scale",
      min: 1,
      max: 5,
      minLabel: "Strongly disagree",
      maxLabel: "Strongly agree",
      domain: "general",
    },
    {
      id: 2,
      text: "I can stay focused on my goals despite setbacks and distractions.",
      type: "scale",
      min: 1,
      max: 5,
      minLabel: "Strongly disagree",
      maxLabel: "Strongly agree",
      domain: "persistence",
    },
    {
      id: 3,
      text: "When I see someone else succeed at something, I believe I can succeed at it too if I put in the effort.",
      type: "scale",
      min: 1,
      max: 5,
      minLabel: "Strongly disagree",
      maxLabel: "Strongly agree",
      domain: "vicarious",
    },
    {
      id: 4,
      text: "I can handle unexpected events or changes in my routine effectively.",
      type: "scale",
      min: 1,
      max: 5,
      minLabel: "Strongly disagree",
      maxLabel: "Strongly agree",
      domain: "adaptability",
    },
    {
      id: 5,
      text: "Describe a recent situation where you successfully overcame a challenge. What strategies did you use?",
      type: "open-ended",
      domain: "reflection",
    },
    {
      id: 6,
      text: "When I receive constructive criticism, I typically:",
      type: "multiple-choice",
      options: [
        { id: "a", text: "Take it personally and feel discouraged", score: 1 },
        { id: "b", text: "Listen but often dismiss it", score: 2 },
        { id: "c", text: "Consider it but may not change my approach", score: 3 },
        { id: "d", text: "Appreciate it and use it to improve", score: 5 },
      ],
      domain: "feedback",
    },
    {
      id: 7,
      text: "I believe my abilities in sports and academics can improve significantly with effort and practice.",
      type: "scale",
      min: 1,
      max: 5,
      minLabel: "Strongly disagree",
      maxLabel: "Strongly agree",
      domain: "growth-mindset",
    },
    {
      id: 8,
      text: "What is your biggest strength that helps you succeed in challenging situations?",
      type: "open-ended",
      domain: "strengths",
    },
  ],
  domains: {
    general: "Overall Self-Efficacy",
    persistence: "Persistence Through Challenges",
    vicarious: "Learning from Others' Success",
    adaptability: "Adaptability to Change",
    reflection: "Self-Reflection",
    feedback: "Response to Feedback",
    "growth-mindset": "Growth Mindset",
    strengths: "Self-Awareness of Strengths",
  },
  scoring: {
    algorithm: "weighted",
    scaleWeight: 1,
    multipleChoiceWeight: 1.5,
    openEndedEvaluation: [
      {
        domain: "reflection",
        keywords: ["plan", "strategy", "step", "approach", "method", "technique", "system", "process"],
        positiveIndicators: ["specific", "detailed", "structured", "organized", "systematic"],
        negativeIndicators: ["vague", "unclear", "confused", "disorganized"],
      },
      {
        domain: "strengths",
        keywords: ["determination", "focus", "discipline", "resilience", "adaptability", "confidence", "persistence"],
        positiveIndicators: ["specific examples", "self-awareness", "realistic assessment"],
        negativeIndicators: ["overly general", "lack of specificity", "unrealistic"],
      },
    ],
  },
  interpretation: {
    ranges: [
      { min: 0, max: 40, level: "developing", label: "Developing Self-Efficacy" },
      { min: 41, max: 70, level: "moderate", label: "Moderate Self-Efficacy" },
      { min: 71, max: 100, level: "strong", label: "Strong Self-Efficacy" },
    ],
    domainThresholds: {
      general: { low: 3, high: 4 },
      persistence: { low: 3, high: 4 },
      vicarious: { low: 3, high: 4 },
      adaptability: { low: 3, high: 4 },
      feedback: { low: 3, high: 4 },
      "growth-mindset": { low: 3, high: 4 },
    },
  },
  recommendations: {
    developing: [
      "Practice setting small, achievable goals to build confidence",
      "Keep a success journal to document your achievements",
      "Find a mentor who can provide positive feedback and encouragement",
      "Use visualization techniques to imagine yourself succeeding",
    ],
    moderate: [
      "Challenge yourself with increasingly difficult tasks",
      "Analyze setbacks to identify specific areas for improvement",
      "Develop specific strategies for managing stress during high-pressure situations",
      "Seek out constructive feedback from coaches and teachers",
    ],
    strong: [
      "Mentor others to reinforce your own skills and knowledge",
      "Set ambitious long-term goals that push your boundaries",
      "Explore new domains where you can apply your self-efficacy",
      "Reflect on your strategies to identify what works best for you",
    ],
  },
}
